# Generated by Django 3.1.14 on 2022-02-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20220222_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.ManyToManyField(blank=True, to='employees.Shift'),
        ),
    ]
